Remove dependency on generate credentials build phase from UI tests
We don't need the dependency on the `GenerateCredentials` aggregate
target to be explicit in the UI tests target because it depends on the
app target, which in turn depends `GenerateCredentials`.

I implemented this as an attempt to address the following error I'm
getting at build time:

```
error: input file '/Users/gio/Developer/a8c/wcios/WooCommerce/DerivedSources/ApiCredentials.swift' was modified during the build
error: input file '/Users/gio/Developer/a8c/wcios/WooCommerce/DerivedSources/ApiCredentials.swift' was modified during the build
Command CompileSwiftSources failed with a nonzero exit code
```

Unfortunately, it didn't solve the issue.

This issue, by the way, seems to be an new thing in Xcode 13.
See here:

https://stackoverflow.com/questions/69256241/xcode-13-error-input-file-was-modified-during-the-build