Define target for variables expansion for UI tests test plan
It's required:

> error: Test Plan Validity: Configuration 'Configuration 1':
> Environment Variables references a build setting but no Target for Variable
> Expansion is specified