Change var name since it seems the Preview dislikes the use of "default".
    Error was:

    Compiling failed: found an unexpected second identifier in variable declaration; is there an accidental break?

    /Users/hafiz/Library/Developer/Xcode/DerivedData/WooCommerce-dbukdzjybkxmrshdiegkriubfgir/Build/Intermediates.noindex/Previews/WooCommerce/Intermediates.noindex/WooCommerce.build/Debug-iphonesimulator/WooCommerce.build/Objects-normal/arm64/ThemesPreviewView.1.preview-thunk.swift:120:72: error: found an unexpected second identifier in variable declaration; is there an accidental break?
        @_dynamicReplacement(for: `default`) private static var __preview__`default`: PreviewDevice {